# Generated by Selenium IDE
from selenium.webdriver.common.by import By
from model.group import Group
from fixture.application import Application
import pytest


@pytest.fixture
def app(request):
    fixture = Application()
    request.addfinalizer(fixture.destroy)
    return fixture


def test_add_group(app):
    # открываем главную страницу
    app.open_home_page()
    app.login(username="admin", password="secret")
    # открываем страницу групп
    app.driver.find_element(By.LINK_TEXT, "groups").click()
    app.create_group(Group(name="444", header="44", footer="4"))
    app.return_to_group()
    app.logout()


def test_empty_group(app):
    # открываем главную страницу
    app.open_home_page()
    app.login(username="admin", password="secret")
    # открываем страницу групп
    app.driver.find_element(By.LINK_TEXT, "groups").click()
    app.create_group(Group(name="", header="", footer=""))
    app.return_to_group()
    app.logout()


